name: maze_action_set_es
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch==1.8.1 py3.7_cpu_0
  - pygraphviz==1.3
  - pip==21.1.1
  - imageio=2.8.0
  - pip:
    - numba==0.54.1
    - grid2op==1.6.0.post1
    - pandapower==2.6.0
    - lightsim2grid==0.5.4
    - maze-rl==0.1.8
    - -e .