# @package wrappers
maze_action_set_es.wrappers.random_chronics_wrapper.RandomChronicsWrapper:
  seeds:
    _target_: maze_action_set_es.env.seeds.seeds_for_power_grid
    power_grid: ${env.core_env.power_grid}
maze_action_set_es.wrappers.critical_state_trainer_wrapper.CriticalStateTrainerWrapper:
  do_skip: true
  raise_exception_on_impossible_seed: false
maze.core.wrappers.spaces_recording_wrapper.SpacesRecordingWrapper: {}
maze.core.wrappers.monitoring_wrapper.MazeEnvMonitoringWrapper:
  observation_logging: false
  action_logging: true
  reward_logging: true